exception: fix bug of memExceptionAddr
For timing optimizaton, just concern mem vaddr's low 39 bits, high
bits are extended from 38bit. When exception happens,
memExceptionAddr should be stored into *tval csr reg.
When high bits may not equal to 38bit, and page fault will be
raised also. So the TRUE high bits should be concerned.